site_name: Deerlay
site_url: https://your-username.github.io/your-project/
repo_url: https://github.com/PRFina/deerlay

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.sections
    - search.suggest
    - search.highlight

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search
  - markdown-exec
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            show_signature_annotations: true

nav:
  - Home: index.md
  - User Guide:
      - Installation: guide/install.md
      - Concepts: guide/concepts.md
      - Extending deerlay: guide/extending.md
  - API Reference: reference/deerlay/index.md

watch:
  - src/deerlay
