site_name: deerlay
site_url: https://your-username.github.io/your-project/
repo_url: https://github.com/PRFina/deerlay

theme:
  name: material
  features:
    - content.code.copy
    - navigation.sections
    - search.suggest
    - search.highlight

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            show_signature_annotations: true

nav:
  - Home: index.md
  - API Reference: reference/deerlay/index.md

watch:
  - src/deerlay
